apiVersion: v1
kind: Service
metadata:
  name: cynovela-svc
  namespace: cynovela
  labels:
    app: cynovela
spec:
  type: NodePort
  selector:
    app: cynovela
  ports:
    - name: http
      port: 8765
      targetPort: 8765
      nodePort: 30080
