"""Reports endpoints (/api/reports/*)."""

from __future__ import annotations

from datetime import datetime

from core.api_schema import parse_body_pydantic
from fastapi import APIRouter, Request

from db import get_db, new_id
from core.errors import api_error

router = APIRouter(tags=["reports"])


@router.post("/api/reports/generate", response_model=None)
async def generate_report(request: Request):
    """LLM で運用サマリーレポートを生成して reports テーブルに保存.

    admin 限定。
    """
    from core.auth import _require_role
    from core.llm import _call_llm_simple
    from server import (
        _REPORT_PROMPTS,
        collect_report_stats,
        log_admin_change,
    )

    user = _require_role(request, {"admin"})
    body = await parse_body_pydantic(request)
    rt = (body.get("report_type") or "monthly").strip().lower()
    if rt not in _REPORT_PROMPTS:
        raise api_error("BAD_REQUEST", "report_type must be one of monthly/poc/technical", status=400)
    days = int(body.get("days") or 30)
    stats = collect_report_stats(days)
    stats_block = "\n".join(f"- {k}: {v}" for k, v in stats.items())
    prompt = _REPORT_PROMPTS[rt].format(stats_block=stats_block, **stats)
    content = await _call_llm_simple(prompt, max_tokens=900)
    # P0-1: タプル返却に対する防御 (core/llm.py 側でも対処済みだが二重防御)
    if isinstance(content, tuple):
        content = content[0]
    rid = new_id()
    conn = get_db()
    try:
        conn.execute(
            "INSERT INTO reports (id, report_type, content, generated_at, "
            "generated_by, days_covered) VALUES (?, ?, ?, ?, ?, ?)",
            (rid, rt, content, datetime.now().isoformat(timespec="seconds"), user["id"], days),
        )
        conn.commit()
    finally:
        conn.close()
    log_admin_change(user["id"], "report", rid, "create", None, {"report_type": rt, "days": days})
    return {
        "id": rid,
        "report_type": rt,
        "content": content,
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "stats": stats,
        "warning": "This report is auto-generated by the system (self-observation log). "
        "Human review is recommended before relying on this content.",
    }


@router.get("/api/reports", response_model=None)
def list_reports(request: Request):
    """admin 限定."""
    from core.auth import _require_role

    _require_role(request, {"admin"})
    conn = get_db()
    try:
        rows = conn.execute(
            "SELECT id, report_type, generated_at, generated_by, days_covered "
            "FROM reports ORDER BY generated_at DESC LIMIT 20"
        ).fetchall()
    finally:
        conn.close()
    return {"reports": [dict(r) for r in rows]}


@router.get("/api/reports/{report_id}", response_model=None)
def get_report(report_id: str, request: Request):
    """admin 限定."""
    from core.auth import _require_role

    _require_role(request, {"admin"})
    conn = get_db()
    try:
        row = conn.execute(
            "SELECT * FROM reports WHERE id = ?",
            (report_id,),
        ).fetchone()
    finally:
        conn.close()
    if not row:
        raise api_error("REPORT_NOT_FOUND", "Report not found", status=404)
    return dict(row)
